# Generated by Django 6.1.1 on 2026-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('javascript', 'JavaScript'), ('hr', 'HR')], max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer_tip', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated words used to match career profiles.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['topic', 'id'],
            },
        ),
    ]
