# Generated by Django 6.1.1 on 2026-10-06 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('current_role', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('junior', '1–2 Years'), ('mid', '3–5 Years'), ('senior', '5+ Years')], max_length=20)),
                ('target_role', models.CharField(max_length=100)),
                ('skills', models.TextField(help_text='Enter your skills separated by commas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
